import {
  Mountain,
  Moon,
  Users,
  Coffee,
  Pizza,
  Bike,
  Plane,
  Camera,
  Music,
  Gamepad2,
  Book,
  Tent,
  Utensils,
  Gift,
  TreePalm,
} from "lucide-react";

const groupList = [
  {
    id: 1,
    name: "Pendakian Gunung Merbabu",
    icon: Mountain,
    color: "bg-green-100 text-green-600",
    total_expenses: 300000,
    expense_count: 3,
    member_count: 3,
  },
  {
    id: 2,
    name: "Bukber di Kala Senja",
    icon: Moon,
    color: "bg-indigo-100 text-indigo-600",
    total_expenses: 450000,
    expense_count: 5,
    member_count: 6,
  },
  {
    id: 3,
    name: "Patungan Nongkrong Weekend",
    icon: Coffee,
    color: "bg-amber-100 text-amber-600",
    total_expenses: 220000,
    expense_count: 4,
    member_count: 4,
  },
  {
    id: 4,
    name: "Makan Pizza Bareng",
    icon: Pizza,
    color: "bg-red-100 text-red-600",
    total_expenses: 180000,
    expense_count: 2,
    member_count: 3,
  },
  {
    id: 5,
    name: "Trip Jogja - Pantai Selatan",
    icon: Plane,
    color: "bg-sky-100 text-sky-600",
    total_expenses: 1250000,
    expense_count: 8,
    member_count: 5,
  },
  {
    id: 6,
    name: "Gowes Minggu Pagi",
    icon: Bike,
    color: "bg-lime-100 text-lime-600",
    total_expenses: 90000,
    expense_count: 2,
    member_count: 4,
  },
  {
    id: 7,
    name: "Fotografi Street Jogja",
    icon: Camera,
    color: "bg-purple-100 text-purple-600",
    total_expenses: 150000,
    expense_count: 3,
    member_count: 3,
  },
  {
    id: 8,
    name: "Acoustic Night",
    icon: Music,
    color: "bg-pink-100 text-pink-600",
    total_expenses: 320000,
    expense_count: 4,
    member_count: 5,
  },
  {
    id: 9,
    name: "Gaming Bareng Sabtu Malam",
    icon: Gamepad2,
    color: "bg-violet-100 text-violet-600",
    total_expenses: 200000,
    expense_count: 3,
    member_count: 4,
  },
  {
    id: 10,
    name: "Book Club Bulanan",
    icon: Book,
    color: "bg-orange-100 text-orange-600",
    total_expenses: 75000,
    expense_count: 1,
    member_count: 3,
  },
  {
    id: 11,
    name: "Camping Ceria",
    icon: Tent,
    color: "bg-emerald-100 text-emerald-600",
    total_expenses: 680000,
    expense_count: 6,
    member_count: 5,
  },
  {
    id: 12,
    name: "Kulineran Malioboro",
    icon: Utensils,
    color: "bg-yellow-100 text-yellow-600",
    total_expenses: 260000,
    expense_count: 4,
    member_count: 4,
  },
  {
    id: 13,
    name: "Patungan Kado Ulang Tahun",
    icon: Gift,
    color: "bg-rose-100 text-rose-600",
    total_expenses: 350000,
    expense_count: 2,
    member_count: 7,
  },
  {
    id: 14,
    name: "Tanam Pohon Bareng",
    icon: TreePalm,
    color: "bg-teal-100 text-teal-600",
    total_expenses: 120000,
    expense_count: 2,
    member_count: 6,
  },
  {
    id: 15,
    name: "Komunitas Nongkrong Santai",
    icon: Users,
    color: "bg-gray-100 text-gray-600",
    total_expenses: 500000,
    expense_count: 7,
    member_count: 8,
  },
];

export default groupList;
