import {
  Mountain,
  Moon,
  Users,
  Coffee,
  Pizza,
  Bike,
  Plane,
  Camera,
  Music,
  Gamepad2,
  Book,
  Tent,
  Utensils,
  Gift,
  TreePalm,
} from "lucide-react";

const mockFinance = {
  members: [
    {
      _id: "u1",
      name: "Alice",
      emoji: "🧑",
      color: "#7C3AED",
      light: "#EDE9FE",
    },
    { _id: "u2", name: "Bob", emoji: "👦", color: "#0EA5E9", light: "#E0F2FE" },
    {
      _id: "u3",
      name: "Charlie",
      emoji: "🧔",
      color: "#F59E0B",
      light: "#FEF3C7",
    },
  ],

  expenses: [
    {
      _id: "e1",
      name: "Makan Malam",
      paid_by: "u1",
      total_amount: 150000,
      participants: [
        { user_id: "u1", share_amount: 50000 },
        { user_id: "u2", share_amount: 50000 },
        { user_id: "u3", share_amount: 50000 },
      ],
    },
    {
      _id: "e2",
      name: "Transport",
      paid_by: "u2",
      total_amount: 90000,
      participants: [
        { user_id: "u1", share_amount: 30000 },
        { user_id: "u2", share_amount: 30000 },
        { user_id: "u3", share_amount: 30000 },
      ],
    },
    {
      _id: "e3",
      name: "Kopi & Snack",
      paid_by: "u3",
      total_amount: 60000,
      participants: [
        { user_id: "u1", share_amount: 20000 },
        { user_id: "u2", share_amount: 20000 },
        { user_id: "u3", share_amount: 20000 },
      ],
    },
  ],

  balances: [
    { user_id: "u1", amount: 70000 },
    { user_id: "u2", amount: 10000 },
    { user_id: "u3", amount: -80000 },
  ],

  settlements: [
    { from: "u3", to: "u1", amount: 70000 },
    { from: "u3", to: "u2", amount: 10000 },
  ],

  history: {
    u1: [
      { type: "received", from: "u2", amount: 50000, expense: "Makan Malam" },
      { type: "received", from: "u3", amount: 50000, expense: "Makan Malam" },
      { type: "paid", to: "u2", amount: 30000, expense: "Transport" },
      { type: "paid", to: "u3", amount: 20000, expense: "Kopi & Snack" },
      { type: "settlement_received", from: "u3", amount: 70000 },
    ],
    u2: [
      { type: "paid", to: "u1", amount: 50000, expense: "Makan Malam" },
      { type: "received", from: "u1", amount: 30000, expense: "Transport" },
      { type: "received", from: "u3", amount: 30000, expense: "Transport" },
      { type: "paid", to: "u3", amount: 20000, expense: "Kopi & Snack" },
      { type: "settlement_received", from: "u3", amount: 10000 },
    ],
    u3: [
      { type: "paid", to: "u1", amount: 50000, expense: "Makan Malam" },
      { type: "paid", to: "u2", amount: 30000, expense: "Transport" },
      { type: "received", from: "u1", amount: 20000, expense: "Kopi & Snack" },
      { type: "received", from: "u2", amount: 20000, expense: "Kopi & Snack" },
      { type: "settlement_paid", to: "u1", amount: 70000 },
      { type: "settlement_paid", to: "u2", amount: 10000 },
    ],
  },
};

const groupList = [
  {
    id: 1,
    name: "Pendakian Gunung Merbabu",
    icon: Mountain,
    color: "bg-green-100 text-green-600",
    total_expenses: 300000,
    expense_count: 3,
    member_count: 3,
    ...mockFinance,
  },
  {
    id: 2,
    name: "Bukber di Kala Senja",
    icon: Moon,
    color: "bg-indigo-100 text-indigo-600",
    total_expenses: 450000,
    expense_count: 5,
    member_count: 6,
    ...mockFinance,
  },
  {
    id: 3,
    name: "Patungan Nongkrong Weekend",
    icon: Coffee,
    color: "bg-amber-100 text-amber-600",
    total_expenses: 220000,
    expense_count: 4,
    member_count: 4,
    ...mockFinance,
  },
  {
    id: 4,
    name: "Makan Pizza Bareng",
    icon: Pizza,
    color: "bg-red-100 text-red-600",
    total_expenses: 180000,
    expense_count: 2,
    member_count: 3,
    ...mockFinance,
  },
  {
    id: 5,
    name: "Trip Jogja - Pantai Selatan",
    icon: Plane,
    color: "bg-sky-100 text-sky-600",
    total_expenses: 1250000,
    expense_count: 8,
    member_count: 5,
    ...mockFinance,
  },
  {
    id: 6,
    name: "Gowes Minggu Pagi",
    icon: Bike,
    color: "bg-lime-100 text-lime-600",
    total_expenses: 90000,
    expense_count: 2,
    member_count: 4,
    ...mockFinance,
  },
  {
    id: 7,
    name: "Fotografi Street Jogja",
    icon: Camera,
    color: "bg-purple-100 text-purple-600",
    total_expenses: 150000,
    expense_count: 3,
    member_count: 3,
    ...mockFinance,
  },
  {
    id: 8,
    name: "Acoustic Night",
    icon: Music,
    color: "bg-pink-100 text-pink-600",
    total_expenses: 320000,
    expense_count: 4,
    member_count: 5,
    ...mockFinance,
  },
  {
    id: 9,
    name: "Gaming Bareng Sabtu Malam",
    icon: Gamepad2,
    color: "bg-violet-100 text-violet-600",
    total_expenses: 200000,
    expense_count: 3,
    member_count: 4,
    ...mockFinance,
  },
  {
    id: 10,
    name: "Book Club Bulanan",
    icon: Book,
    color: "bg-orange-100 text-orange-600",
    total_expenses: 75000,
    expense_count: 1,
    member_count: 3,
    ...mockFinance,
  },
  {
    id: 11,
    name: "Camping Ceria",
    icon: Tent,
    color: "bg-emerald-100 text-emerald-600",
    total_expenses: 680000,
    expense_count: 6,
    member_count: 5,
    ...mockFinance,
  },
  {
    id: 12,
    name: "Kulineran Malioboro",
    icon: Utensils,
    color: "bg-yellow-100 text-yellow-600",
    total_expenses: 260000,
    expense_count: 4,
    member_count: 4,
    ...mockFinance,
  },
  {
    id: 13,
    name: "Patungan Kado Ulang Tahun",
    icon: Gift,
    color: "bg-rose-100 text-rose-600",
    total_expenses: 350000,
    expense_count: 2,
    member_count: 7,
    ...mockFinance,
  },
  {
    id: 14,
    name: "Tanam Pohon Bareng",
    icon: TreePalm,
    color: "bg-teal-100 text-teal-600",
    total_expenses: 120000,
    expense_count: 2,
    member_count: 6,
    ...mockFinance,
  },
  {
    id: 15,
    name: "Komunitas Nongkrong Santai",
    icon: Users,
    color: "bg-gray-100 text-gray-600",
    total_expenses: 500000,
    expense_count: 7,
    member_count: 8,
    ...mockFinance,
  },
];

export default groupList;
